blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # ABOUT US
    path('', views.aboutView, name = "about" ),
    # SUBJECTS
    path('subjects/', views.subjectsView.as_view(), name = "subjects" ),
    path('subjects/create/', views.subjectCreateView.as_view(success_url="/subjects/"), name = "subjectCreate" ),
    path('subjects/subjectArticles/<int:pk>', views.subjectArticlesListView.as_view(), name = "subjectArticles" ),
    # ARTICLES
    path('articles/detail/<int:pk>/', views.articleDetailView.as_view(), name = "articleDetail" ),
    path('articles/create/<int:pk>', views.articleCreateView.as_view(), name = "articleCreate" ),
    path('articles/delete/<int:pk>/', views.articleDeleteView.as_view(), name = "articleDelete" ),
    path('articles/update/<int:pk>/', views.ArticleUpdateView.as_view(), name = "articleUpdate" ),
    # AUTHOR
    path('authorarticles/<str:username>', views.authorArticlesView.as_view(), name = "authorArticles" ),
    path('authors/', views.authorsListView.as_view(), name = "authors" ),

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('user.urls')),
    # path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


##################################################################
class Subject(models.Model):
    subjectName = models.CharField(max_length=30)
    createdDate = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="defaultSubject.jpg")

    def __str__(self):
        return f'{self.subjectName}'



##################################################################
class Article(models.Model):
    articleSubject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(default="defaultArticle.jpg")  #blank=True, null=True
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:articleDetail', kwargs={'pk': self.pk})
 
##################################################################
class Comment(models.Model):
    relatedPost = models.ForeignKey(Article,on_delete=models.CASCADE)
    commentAuthor = models.CharField(max_length=50)
    commentContent = models.CharField(max_length=1000)
    commentDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.commentContent
    class Meta:
        ordering = ['-commentDate']

blog/forms.py
# SubjectForm (required admin for access)
#     subjectName
#     createdDate automatic
#     image

# PostForm
#     title, textContent, image
#     subject - select
#     author - automatic
#     date - automatic

# Comment
#     post, content
#     author, date - automatic

blog/views.py
# from blogproject import user
from django.urls import reverse
from .models import Subject, Article, Comment
from django.views.generic import (ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.shortcuts import get_list_or_404, render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User


################# ABOUT #######################
def aboutView(request):
    return render(request, 'blog/about.html', {'title': 'About'})


################# SUBJECTS #######################
# -------------------------------------------------- #
#--------- LISTING ALL SUBJECTS ON MAIN PAGE --------#
class subjectsView(ListView):
    model = Subject
    template_name = 'blog/subjects_View.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'subjects'
    ordering = ['-createdDate']
    # paginate_by = 10

# -------------------------------------------------- #
#--------- CREATE NEW SUBJECT -----------------------#
class subjectCreateView(LoginRequiredMixin, CreateView):
    model = Subject
    fields = ['image', 'subjectName']

# -------------------------------------------------- #
#----- DISPLAY ALL ARTICLES OF GIVEN SUBJECT --------#
class subjectArticlesListView(ListView):
    model = Article
    template_name = 'blog/subject_articles.html' 
    context_object_name = 'articles'
    # paginate_by = 10
     
    def get_queryset(self):
        subject = get_object_or_404(Subject, id=self.kwargs.get('pk'))
        return Article.objects.filter(articleSubject=subject) .order_by('-date_posted')




################# ARTICLES #######################

# -------------------------------------------------- #
# ----- DISPLAY SINGLE ARTICLE DETAILS --------------#
class articleDetailView(DetailView):
    model = Article

# -------------------------------------------------- #
# ---------- CREATE NEW ARTICLE  ------------------- #
class articleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = [ 'articleSubject','title', 'content', 'image']

    def form_valid(self, form):
        form.instance.articleSubject = get_object_or_404(Subject, id=self.kwargs.get('pk'))
        form.instance.author = self.request.user
        return super().form_valid(form)

# -------------------------------------------------- #
# ----------------------- DELETE ARTICLE  -----------#
class articleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    success_url = '/subjects/'

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False


# -------------------------------------------------- #
#------------------------ UPDATE ARTICLE  -----------#
class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ['articleSubject', 'title', 'content', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False



################# AUTHOR #######################

# -------------------------------------------------- #
# -------- DISPLAY ALL ARTICLES OF AUTHOR ---------- #

class authorArticlesView(ListView):
    model = Article
    template_name = 'blog/author_articles.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'articles'
    # paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Article.objects.filter(author=user).order_by('-date_posted')


# -------------------------------------------------- #
# -------------- DISPLAY ALL AUTHORS --------------- #

class authorsListView(ListView):
    model = User
    template_name = "blog/authors.html"
    context_object_name= "users"

    # def get_queryset(self): 
    #     return User.objects.filter(User.article_set)


    # # def get_queryset(self):
    # #     return Scenario.objects.filter(
    # #         scenarioAuthor=self.request.user
    # #     ).order_by('-date_posted')

blog/templates/blog/about.html
{% extends "./base.html" %}


{% block content %}

<div class="section section-text">
    <h3>Lorem ipsum dolor sit.</h3>

    <div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius nam
      aperiam dolor corporis pariatur corrupti doloribus, ab provident
      excepturi, dolorum eaque quod, amet in illo aut earum! Nobis rerum
      aliquam rem numquam unde earum esse eaque soluta dolore? Incidunt sit
      quod atque harum perspiciatis necessitatibus quo est nesciunt
      reiciendis. Perferendis reprehenderit nisi autem adipisci. Expedita
      blanditiis quae omnis provident doloribus, labore, fugiat aperiam
      corrupti accusamus error adipisci aspernatur suscipit fuga rerum!
      Architecto, quia? Voluptatum dignissimos labore repellendus facilis,
      dicta temporibus quisquam ipsam tempora est! Neque iusto quasi
      quibusdam, ex exercitationem incidunt, at assumenda obcaecati fugiat,

    </div>

  </div>

    <!--------------------------------------------------->
    <!-- -- SECTION 1 -- ZOOMING IMAGES X6   -->
    <!--------------------------------------------------->
    <div class="section section-1">
      <ul class="forest-images-row">
        <li>
          <figure class="forest-image">
            <img
              src="/media/about/forest/andres-medina-JVUCzgbTjDE-unsplash 1.jpg"
              alt=""
            />
          </figure>
        </li>
        <li>
          <figure class="forest-image">
            <img
              src="/media/about/forest/dave-hoefler-frmovOarYdE-unsplash 1.jpg"
              alt=""
            />
          </figure>
        </li>
        <li>
          <figure class="forest-image">
            <img
              src="/media/about/forest/david-clode-9Qw7qrx5uLc-unsplash 1.jpg"
              alt=""
            />
          </figure>
        </li>
      </ul>
      <ul class="forest-images-row">
        <li>
          <figure class="forest-image">
            <img
              src="/media/about/forest/jaime-dantas-FxJ_ZImQ8Nk-unsplash 1.jpg"
              alt=""
            />
          </figure>
        </li>
        <li>
          <figure class="forest-image">
            <img
              src="/media/about/forest/tommy-krombacher-BHJhNACkD6c-unsplash 1.jpg"
              alt=""
            />
          </figure>
        </li>
        <li>
          <figure class="forest-image">
            <img
              src="/media/about/forest/vlad-hilitanu-pt7QzB4ZLWw-unsplash 1.jpg"
              alt=""
            />
          </figure>
        </li>
      </ul>
    </div>

    <!--------------------------------------------------->
    <!-- SECTION TEXT ----------------------------------->
    <!--------------------------------------------------->

    <div class="section section-text">
      <h3>Lorem ipsum dolor sit.</h3>

      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius nam
        aperiam dolor corporis pariatur corrupti doloribus, ab provident
        excepturi, dolorum eaque quod, amet in illo aut earum! Nobis rerum
        aliquam rem numquam unde earum esse eaque soluta dolore? Incidunt sit
        quod atque harum perspiciatis necessitatibus quo est nesciunt
        reiciendis. Perferendis reprehenderit nisi autem adipisci. Expedita
        blanditiis quae omnis provident doloribus, labore, fugiat aperiam
        corrupti accusamus error adipisci aspernatur suscipit fuga rerum!
        Architecto, quia? Voluptatum dignissimos labore repellendus facilis,
        dicta temporibus quisquam ipsam tempora est! Neque iusto quasi
        quibusdam, ex exercitationem incidunt, at assumenda obcaecati fugiat,
        <br /><br />
        est quo nemo expedita eum? Magnam optio maxime in, facere ea beatae
        rerum hic. Nesciunt veniam, nemo ut minima temporibus repellat, quae
        voluptas fuga culpa consequatur similique, aliquid in autem amet magni?
        Facere debitis aut aliquam repudiandae expedita dolores enim, quibusdam
        ipsa voluptate totam nihil laudantium, quia eius deserunt veniam
        doloremque saepe praesentium. Tempora minus qui iure fugit dolor
        accusamus ipsum a voluptates, sapiente mollitia adipisci possimus. Unde
        autem, nihil, cupiditate quas esse temporibus, odio nulla quibusdam
        mollitia nemo sequi. Dolorem ea quos sapiente quas inventore quisquam
        voluptatem impedit officiis, exercitationem ipsam nobis, consequuntur
        repudiandae necessitatibus. Consectetur facere delectus libero pariatur
        ipsa recusandae aperiam repellendus.
      </div>

    </div>

    <!--------------------------------------------------->
    <!-- SECTION 2 ---- MODULE CARDS SECTION ------------>
    <!--------------------------------------------------->

    <div class="section section-2" id="section-2">


<!---------- MODULE 1 AND MODAL 1 ------------>
        <figure class="module module-1" data-tab="1" data-toggle="modal" data-target="#modal1">
        <!-- module title -->
        <div class="module-title">module title</div>
        <!-- module image -->
        <div class="module-hero">
          <img
            class="module-img"
            src="/media/about/forest/rainbow/stainless-images-JzCf5Y3XmFU-unsplash 1.jpg"
            alt=""
          />
        </div>
        <!-- module description -->
        <div class="module-description">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil dicta
          vitae Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil
          dicta
        </div>
        <div><h5>Click for More Info</h5></div>
      </figure>

  
  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Module 1 Description 🦜</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam in assumenda eaque molestiae, quaerat sed facere, dolorum quos quis dolorem fuga illo nostrum temporibus. Optio reiciendis ducimus, a laudantium assumenda porro vitae libero rem quibusdam, doloremque, illo error laborum quae! Numquam ea repudiandae consequuntur hic adipisci velit totam ut laudantium?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>



<!---------- MODULE 2 AND MODAL 2 ------------>

<figure class="module module-2" data-tab="2" data-toggle="modal" data-target="#modal2">
    <!-- module title -->
        <div class="module-title">module title</div>
        <!-- module image -->
        <div class="module-hero">
          <img
            class="module-img"
            src="/media/about/forest/rainbow/mike-schrengohst-JlnSnRIZ5fA-unsplash.jpg"
            alt=""
          />
        </div>
        <!-- module description -->
        <div class="module-description">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil dicta
          vitae Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil
          dicta
        </div>
        <div><h5>Click for More Info</h5></div>
      </figure>

        
  <div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Module 2 Description 🦜</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam in assumenda eaque molestiae, quaerat sed facere, dolorum quos quis dolorem fuga illo nostrum temporibus. Optio reiciendis ducimus, a laudantium assumenda porro vitae libero rem quibusdam, doloremque, illo error laborum quae! Numquam ea repudiandae consequuntur hic adipisci velit totam ut laudantium?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>



      <figure class="module module-2" data-tab="3" data-toggle="modal" data-target="#modal3">
        <!-- module title -->
        <div class="module-title">module title</div>
        <!-- module image -->
        <div class="module-hero">
          <img
            class="module-img"
            src="/media/about/forest/rainbow/eberhard-grossgasteiger-6R3dGQJ3qOI-unsplash 1.jpg"
            alt=""
          />
        </div>
        <!-- module description -->
        <div class="module-description">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil dicta
          vitae Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil
          dicta
        </div>
        <div><h5>Click for More Info</h5></div>
      </figure>

      <div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Module 3 Description 🦜</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam in assumenda eaque molestiae, quaerat sed facere, dolorum quos quis dolorem fuga illo nostrum temporibus. Optio reiciendis ducimus, a laudantium assumenda porro vitae libero rem quibusdam, doloremque, illo error laborum quae! Numquam ea repudiandae consequuntur hic adipisci velit totam ut laudantium?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


      <figure class="module module-4" data-tab="4" data-toggle="modal" data-target="#modal4">
        <!-- module title -->
        <div class="module-title">module title</div>
        <!-- module image -->
        <div class="module-hero">
          <img
            class="module-img"
            src="/media/about/forest/rainbow/isaac-quesada-Hof8Lw1d4Bk-unsplash 1.jpg"
            alt=""
          />
        </div>
        <!-- module description -->
        <div class="module-description">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil dicta
          vitae Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil
          dicta
        </div>
        <div><h5>Click for More Info</h5></div>
      </figure>
    </div>

    <div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Module 3 Description 🦜</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam in assumenda eaque molestiae, quaerat sed facere, dolorum quos quis dolorem fuga illo nostrum temporibus. Optio reiciendis ducimus, a laudantium assumenda porro vitae libero rem quibusdam, doloremque, illo error laborum quae! Numquam ea repudiandae consequuntur hic adipisci velit totam ut laudantium?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


 






{% endblock content %}

blog/templates/blog/article_ListView.html
{% extends "./base.html" %}

blog/templates/blog/article_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section delete-page">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Article</legend>
                <h2>Are you sure you want to delete the article :</h2>
                <h2>"{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-secondary" href="{% url 'blog:articleDetail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/article_detail.html
{% extends "./base.html" %}


{% load static %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/article.css' %}">
{% endblock %}


{% block content %}
<div class="article">

  <div class="left-column">
    <div class="article-profile-section">
      <div class="article-profile-image"> <img src="{{ object.author.profile.image.url }}" alt=""></div>
      <!-- <div class="article-profile-username">Author: {{ object.author.username |upper }}</div> -->
      <a class="mr-2 author-link" href="{% url 'public_profile' object.author.username %}">{{ object.author.username | upper }}</a>

    </div>
    <div class="article-date">Posted: {{ object.date_posted|date:"F d, Y" }}
    </div>
    {% if object.author == user %}
    <div > 
      <a class="btn btn-secondary btn-sm mt-2 mb-1 article-update-button" href="{% url 'blog:articleUpdate' object.id %}">Update</a>
      <a class="btn btn-danger btn-sm mt-2 mb-1 article-delete-button" href="{% url 'blog:articleDelete' object.id %}">Delete</a>
    </div>
  {% endif %}
  </div>

  <div class="right-column">
    <div class="article-title"  >{{ object.title }}
    </div>
    <div class="article-body">{{ object.content }}</div>
  </div>
</div>
{% endblock content %}

blog/templates/blog/article_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="article-form-content-section">
        {{ object.articleSubject.subjectName }} hello
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <!-- <legend class="border-bottom mb-4">Blog Article</legend> -->
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Post Article</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/author_articles.html
{% extends "./base.html" %}

{% block content %}

<!-- <div style="margin: 3rem;" >  {{ view.kwargs.pk }} </div> -->


<div class="subject-articles-container" id="subject-articles-container">
    {% for article in articles %}

        <div class="single-article-card" data-article_id="{{article.id}}" >  

                    <div>
                        <div class="article-image-box"><img class="article-image" src="{{article.image.url}}" alt=""></div>
                    </div>
                    <div class="title-content-date">
                        <div class="article-title-box">{{article.title|truncatechars:50}} </div>
                        <div class="article-content-box">{{article.content|truncatechars:450}} </div>
                        <div class="article-date-box">Posted on {{article.date_posted  | date:'F d, Y'|upper}} by {{article.author|upper}} </div>
                    </div>
        </div>
    {% endfor %}
</div>



{% endblock %}

blog/templates/blog/authors.html
{% extends "./base.html" %}

{% block content %}

<div class="allusers-profile-container" id="allusers-profile-container"> 
{% for user in users %}
    <div class="allusers-profile" data-username="{{user.username}}" >
        <img class="profile-image-allusers"  src="{{ user.profile.image.url }}">
        <div class="profile-name-allusers">{{user.username}}</div>
    </div>
<!-- {% if user.article_set.count != 0 %} -->

   <!-- {% endif %} -->
{% endfor %}

</div>
{% endblock %}

blog/templates/blog/navbar.html
<nav class="navbar  navbar-expand-lg" 
style=" color: #0154d5;
background-image: radial-gradient(rgba(11, 73, 114, 0.869),rgba(8, 53, 83, 0.9));">
<!-- background-image: radial-gradient(#0b4972,#083553);"> -->

<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <a class="navbar-brand" href="{% url 'blog:about' %}">Social Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:subjects' %}">Subjects <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:authors' %}">Authors</a>
        </li>
      </ul>
      <div class="navbar-nav">
        {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        {% endif %}
      </div>
    </div>
  </nav>

blog/templates/blog/subject_articles.html
{% extends "./base.html" %}

{% block content %}


{% for article in articles %}
    {% if forloop.first %}  
    <div class="title-and-button">
        <div class="subject-articles-subject-name">{{article.articleSubject.subjectName|truncatechars:100}}</div>
        <a class="add-new-article-button" href="{% url 'blog:articleCreate' view.kwargs.pk  %}">
            <button class="btn btn-info add-new-article-button ">Add New Article </button>
        </a>
    </div>
    {% endif %} 
{% endfor %}

{% if not articles %}
<div class="button-in-empty-page">
    <a class="add-new-article-button" href="{% url 'blog:articleCreate'  view.kwargs.pk  %}">
        <button class="btn btn-info add-new-article-button ">Add New Article </button>
    </a>
</div>
{% endif %}

<div class="subject-articles-container" id="subject-articles-container">
    {% for article in articles %}

        <div class="single-article-card" data-article_id="{{article.id}}" >  
                    <!-- {% if article.image %} -->
                    <!-- {% endif %} -->
                    <div>
                        <div class="article-image-box"><img class="article-image" src="{{article.image.url}}" alt=""></div>
                    </div>
                    <div class="title-content-date">
                        <div class="article-title-box">{{article.title|truncatechars:50}} </div>
                        <div class="article-content-box">{{article.content|truncatechars:450}} </div>
                        <div class="article-date-box">Posted on {{article.date_posted  | date:'F d, Y'|upper}} by {{article.author|upper}} </div>
                    </div>
        </div>
    {% endfor %}
</div>




{% endblock %}

blog/templates/blog/subject_form.html
{% extends "./base.html" %}


{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section add-new-subject">
        <form  method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
             Subject Name can have 30 charcters max. <br><br>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Create New Subject</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/subjects_View.html
{% extends "./base.html" %}

{% block content %}
<div class="all-subjects-container" id="all-subjects-container">
    {% for subject in subjects %}
        <div class="single-subject-card" data-subject_id="{{subject.id}}" >
                    <div class="subject-title-box" >{{subject.subjectName}} </div>
                    <div class="subject-image-box"><img class="subject-image" src="{{subject.image.url}}" alt=""></div>
                    <div class="subject-date-box"> <strong>{{subject.article_set.count}}</strong> articles since <strong>{{subject.createdDate | date:'F d, Y'}}</strong></div> 
        </div>
    {% endfor %}
</div>

{% if user.is_superuser %}
<a class="add-subject-button" href="{% url 'blog:subjectCreate' %}">
    <button class="btn btn-info ">Add New Subject </button>
</a>
{% endif %}

{% endblock %}