blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # ABOUT US
    path('', views.aboutView, name = "about" ),
    # SUBJECTS
    path('subjects/', views.subjectsView.as_view(), name = "subjects" ),
    path('subjects/create/', views.subjectCreateView.as_view(success_url="/subjects/"), name = "subjectCreate" ),
    path('subjects/subjectArticles/<int:pk>', views.subjectArticlesListView.as_view(), name = "subjectArticles" ),
    # ARTICLES
    path('articles/detail/<int:pk>/', views.articleDetailView.as_view(), name = "articleDetail" ),
    path('articles/create/<int:pk>', views.articleCreateView.as_view(), name = "articleCreate" ),
    path('articles/delete/<int:pk>/', views.articleDeleteView.as_view(), name = "articleDelete" ),
    path('articles/update/<int:pk>/', views.ArticleUpdateView.as_view(), name = "articleUpdate" ),
    # AUTHOR
    path('authorarticles/<str:username>', views.authorArticlesView.as_view(), name = "authorArticles" ),
    path('authors/', views.authorsListView.as_view(), name = "authors" ),

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('user.urls')),
    # path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


# app_name = "user"

urlpatterns = [
    # USER RELATED
    path('register/', views.register, name='register'),    
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),


    # PROFILE
    path('profile/', views.profile, name='profile'),
    path('public_profile/<str:username>', views.publicProfile.as_view(template_name ="user/public_profile.html"), name='public_profile'),

    # path('authorarticles/<str:username>', views.authorArticlesView.as_view(), name = "authorArticles" ),


    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='user/password_reset.html'),name='password_reset'),

    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='user/password_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'),name='password_reset_complete'),

   ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


##################################################################
class Subject(models.Model):
    subjectName = models.CharField(max_length=30)
    createdDate = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="defaultSubject.jpg")

    def __str__(self):
        return f'{self.subjectName}'



##################################################################
class Article(models.Model):
    articleSubject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(default="defaultArticle.jpg")  #blank=True, null=True
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:articleDetail', kwargs={'pk': self.pk})
 
##################################################################
class Comment(models.Model):
    relatedPost = models.ForeignKey(Article,on_delete=models.CASCADE)
    commentAuthor = models.CharField(max_length=50)
    commentContent = models.CharField(max_length=1000)
    commentDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.commentContent
    class Meta:
        ordering = ['-commentDate']

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=100)
    image = models.ImageField(default="defaultProfile.jpg", upload_to= "profile_images")
    facebook = models.CharField(max_length=200, blank=True, null=True)
    instagram = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [ "facebook", "instagram",'image']

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic import DetailView
from django.contrib.auth.models import User
from django.shortcuts import get_list_or_404, render, get_object_or_404


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'user/profile.html', context)



class publicProfile(ListView):
    model = User
    context_object_name = 'profile_users'

    def get_queryset(self):
        # user = get_object_or_404(User, username=self.kwargs.get('username'))
        return User.objects.filter(username=self.kwargs.get('username'))
        # return User.objects.filter(username=self.kwargs.get('username'))
            # return User.objects.filter(author=user).order_by('-date_posted')


# class authorArticlesView(ListView):
#     model = Article
#     template_name = 'blog/author_articles.html'  # <app>/<model>_<viewtype>.html
#     context_object_name = 'articles'
#     # paginate_by = 10

#     def get_queryset(self):
#         user = get_object_or_404(User, username=self.kwargs.get('username'))
#         return Article.objects.filter(author=user).order_by('-date_posted')

user/templates/user/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section  user-page">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group "style="background-color: rgba(255, 255, 255, 0.103); padding: 2rem;">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group" >
                <button class="btn btn-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

user/templates/user/logout.html
{% extends "blog/base.html" %}
{% block content %}
<div class="content-section  user-page">

    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <a class="ml-2" href="{% url 'login' %}">Login Again</a>
    </div>

</div>

{% endblock content %}

user/templates/user/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section  user-page">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

user/templates/user/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

user/templates/user/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section  user-page">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

user/templates/user/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

user/templates/user/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section  user-page">

      <div class="profile-section-all">
        <div class="profile-image-section">
          <img class="profile-image" src="{{ user.profile.image.url }}">
        </div>

          <div class="profile-information-section">
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/user.png" alt=""></div>
          <div class="profile-info-item">{{ user.username }}</div>

          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/email.png" alt=""></div>
          <div class="profile-info-item">{{ user.profile.email }}</div>
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/facebook.jpg" alt=""></div>
          <div class="profile-info-item" > {% if user.profile.facebook %}{{ user.profile.facebook|truncatechars:50 }}{% else %} &nbsp  {% endif %} </div>
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/instagram.png" alt=""></div>
          <div class="profile-info-item"> {% if user.profile.instagram %}{{ user.profile.instagram|truncatechars:50 }}  {% else %} &nbsp  {% endif %}</div>
        </div>
      </div>


      <div class="form-group mt-3">
        <!-- <button class="btn btn-info" type="submit">Articles</button> -->
        <a class="btn btn-primary" href="{% url 'blog:authorArticles' user.username %}">Go to my Articles</a>
    </div>

      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group"  style="background-color: rgba(255, 255, 255, 0.103); padding: 2rem;">
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-info" type="submit">Update</button>
          </div>
      </form>

    </div>

{% endblock content %}

user/templates/user/public_profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="content-section  user-page">
      <div class="profile-section-all">
        <div class="profile-image-section">
          {% for user in profile_users%}
          <img class="profile-image" src="{{ user.profile.image.url }}">
       {% endfor %}
        </div>
        {% for user in profile_users%}
        <div class="profile-information-section">
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/user.png" alt=""></div>
          <div class="profile-info-item">{{ user.username }}</div>
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/email.png" alt=""></div>
          <div class="profile-info-item">{{ user.profile.email }}</div>
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/facebook.jpg" alt=""></div>
          <div class="profile-info-item" > {% if user.profile.facebook %}{{ user.profile.facebook|truncatechars:50 }}{% else %} &nbsp  {% endif %} </div>
          <div class="profile-info-item" class="social-image"><img class="social-img" src="/static/instagram.png" alt=""></div>
          <div class="profile-info-item"> {% if user.profile.instagram %}{{ user.profile.instagram|truncatechars:50 }}  {% else %}  &nbsp  {% endif %}</div>
         
        </div>
        {% endfor %}
       </div>
        {% for user in profile_users%}
        {% if user.article_set.count %}

        <div class="form-group mt-3">
              <!-- <button class="btn btn-info" type="submit">Articles</button> -->
              <a class="btn btn-primary" href="{% url 'blog:authorArticles' user.username %}">Go to   {{user.username|upper}}'s   Articles</a>
          </div>        
          {% endif %}

          {% endfor %}

    </div>
{% endblock content %}

user/templates/user/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section user-page">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group" style="background-color: rgba(255, 255, 255, 0.103); padding: 2rem;">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}